language: python

rvm:
    - 3.6.8

install:
    - pip install ./
    - pip install pytest-cov
    - pip install coveralls

script: export PYTHONPATH=. && pytest --cov=netcutter/ tests/

after_success:
    - coveralls
